from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1120, 630)
        Form.setStyleSheet("background-color:#59baea;")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushbt_back = QtWidgets.QPushButton(Form)
        self.pushbt_back.setStyleSheet("background-color: #f4511e;\n"
                                       "color: white;\n"
                                       "padding: 16px 32px;\n"
                                       "text-align: center;\n"
                                       "font-size: 16px;\n"
                                       "margin: 4px 2px;\n"
                                       "font-weight:bold;")
        self.pushbt_back.setObjectName("pushbt_back")
        self.horizontalLayout_5.addWidget(self.pushbt_back)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:red;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.horizontalLayout_5.setStretch(0, 3)
        self.horizontalLayout_5.setStretch(1, 7)
        self.horizontalLayout_5.setStretch(2, 5)
        self.horizontalLayout_5.setStretch(3, 10)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.le_name = QtWidgets.QLineEdit(Form)
        self.le_name.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.le_name.setMaxLength(32)
        self.le_name.setObjectName("le_name")
        self.horizontalLayout_4.addWidget(self.le_name)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.lb_nameico = QtWidgets.QLabel(Form)
        self.lb_nameico.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_nameico.setObjectName("lb_nameico")
        self.horizontalLayout_4.addWidget(self.lb_nameico)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.horizontalLayout_4.setStretch(0, 12)
        self.horizontalLayout_4.setStretch(1, 10)
        self.horizontalLayout_4.setStretch(2, 2)
        self.horizontalLayout_4.setStretch(3, 16)
        self.horizontalLayout_4.setStretch(4, 2)
        self.horizontalLayout_4.setStretch(5, 1)
        self.horizontalLayout_4.setStretch(6, 14)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.label_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.le_username = QtWidgets.QLineEdit(Form)
        self.le_username.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.le_username.setMaxLength(32)
        self.le_username.setObjectName("le_username")
        self.horizontalLayout_3.addWidget(self.le_username)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.lb_usernameico = QtWidgets.QLabel(Form)
        self.lb_usernameico.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_usernameico.setObjectName("lb_usernameico")
        self.horizontalLayout_3.addWidget(self.lb_usernameico)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.horizontalLayout_3.setStretch(0, 12)
        self.horizontalLayout_3.setStretch(1, 10)
        self.horizontalLayout_3.setStretch(2, 2)
        self.horizontalLayout_3.setStretch(3, 16)
        self.horizontalLayout_3.setStretch(4, 2)
        self.horizontalLayout_3.setStretch(5, 1)
        self.horizontalLayout_3.setStretch(6, 14)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem12)
        self.label_4 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem13)
        self.le_password = QtWidgets.QLineEdit(Form)
        self.le_password.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.le_password.setMaxLength(32)
        self.le_password.setObjectName("le_password")
        self.horizontalLayout.addWidget(self.le_password)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem14)
        self.lb_passwordico = QtWidgets.QLabel(Form)
        self.lb_passwordico.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_passwordico.setObjectName("lb_passwordico")
        self.horizontalLayout.addWidget(self.lb_passwordico)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem15)
        self.horizontalLayout.setStretch(0, 12)
        self.horizontalLayout.setStretch(1, 10)
        self.horizontalLayout.setStretch(2, 2)
        self.horizontalLayout.setStretch(3, 16)
        self.horizontalLayout.setStretch(4, 2)
        self.horizontalLayout.setStretch(5, 1)
        self.horizontalLayout.setStretch(6, 14)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem16)
        self.label_5 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem17)
        self.le_confirmpassword = QtWidgets.QLineEdit(Form)
        self.le_confirmpassword.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.le_confirmpassword.setMaxLength(32)
        self.le_confirmpassword.setObjectName("le_confirmpassword")
        self.horizontalLayout_9.addWidget(self.le_confirmpassword)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem18)
        self.lb_confirmpasswordico = QtWidgets.QLabel(Form)
        self.lb_confirmpasswordico.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_confirmpasswordico.setObjectName("lb_confirmpasswordico")
        self.horizontalLayout_9.addWidget(self.lb_confirmpasswordico)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem19)
        self.horizontalLayout_9.setStretch(0, 12)
        self.horizontalLayout_9.setStretch(1, 10)
        self.horizontalLayout_9.setStretch(2, 2)
        self.horizontalLayout_9.setStretch(3, 16)
        self.horizontalLayout_9.setStretch(4, 2)
        self.horizontalLayout_9.setStretch(5, 1)
        self.horizontalLayout_9.setStretch(6, 14)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem20)
        self.label_6 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem21)
        self.le_phone = QtWidgets.QLineEdit(Form)
        self.le_phone.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.le_phone.setMaxLength(10)
        self.le_phone.setObjectName("le_phone")
        self.horizontalLayout_8.addWidget(self.le_phone)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem22)
        self.lb_phoneico = QtWidgets.QLabel(Form)
        self.lb_phoneico.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_phoneico.setObjectName("lb_phoneico")
        self.horizontalLayout_8.addWidget(self.lb_phoneico)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem23)
        self.horizontalLayout_8.setStretch(0, 12)
        self.horizontalLayout_8.setStretch(1, 10)
        self.horizontalLayout_8.setStretch(2, 2)
        self.horizontalLayout_8.setStretch(3, 16)
        self.horizontalLayout_8.setStretch(4, 2)
        self.horizontalLayout_8.setStretch(5, 1)
        self.horizontalLayout_8.setStretch(6, 14)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem24)
        self.label_7 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem25)
        self.le_email = QtWidgets.QLineEdit(Form)
        self.le_email.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.le_email.setMaxLength(50)
        self.le_email.setObjectName("le_email")
        self.horizontalLayout_7.addWidget(self.le_email)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem26)
        self.lb_emailico = QtWidgets.QLabel(Form)
        self.lb_emailico.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_emailico.setObjectName("lb_emailico")
        self.horizontalLayout_7.addWidget(self.lb_emailico)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem27)
        self.horizontalLayout_7.setStretch(0, 12)
        self.horizontalLayout_7.setStretch(1, 10)
        self.horizontalLayout_7.setStretch(2, 2)
        self.horizontalLayout_7.setStretch(3, 16)
        self.horizontalLayout_7.setStretch(4, 2)
        self.horizontalLayout_7.setStretch(5, 1)
        self.horizontalLayout_7.setStretch(6, 14)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem28)
        self.label_8 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem29)
        self.le_recoveryhint = QtWidgets.QLineEdit(Form)
        self.le_recoveryhint.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.le_recoveryhint.setMaxLength(32)
        self.le_recoveryhint.setObjectName("le_recoveryhint")
        self.horizontalLayout_6.addWidget(self.le_recoveryhint)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem30)
        self.lb_recoveryhintico = QtWidgets.QLabel(Form)
        self.lb_recoveryhintico.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_recoveryhintico.setObjectName("lb_recoveryhintico")
        self.horizontalLayout_6.addWidget(self.lb_recoveryhintico)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem31)
        self.horizontalLayout_6.setStretch(0, 12)
        self.horizontalLayout_6.setStretch(1, 10)
        self.horizontalLayout_6.setStretch(2, 2)
        self.horizontalLayout_6.setStretch(3, 16)
        self.horizontalLayout_6.setStretch(4, 2)
        self.horizontalLayout_6.setStretch(5, 1)
        self.horizontalLayout_6.setStretch(6, 14)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem32 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem32)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.le_adminusername = QtWidgets.QLineEdit(self.groupBox)
        self.le_adminusername.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.le_adminusername.setMaxLength(32)
        self.le_adminusername.setObjectName("le_adminusername")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_adminusername)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.le_adminpassword = QtWidgets.QLineEdit(self.groupBox)
        self.le_adminpassword.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.le_adminpassword.setObjectName("le_adminpassword")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_adminpassword)
        self.horizontalLayout_11.addWidget(self.groupBox)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem33)
        self.lb_admindetailsico = QtWidgets.QLabel(Form)
        self.lb_admindetailsico.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_admindetailsico.setObjectName("lb_admindetailsico")
        self.horizontalLayout_11.addWidget(self.lb_admindetailsico)
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem34)
        self.horizontalLayout_11.setStretch(0, 10)
        self.horizontalLayout_11.setStretch(1, 2)
        self.horizontalLayout_11.setStretch(2, 1)
        self.horizontalLayout_11.setStretch(3, 10)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem35)
        self.lb_warning = QtWidgets.QLabel(Form)
        self.lb_warning.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_warning.setObjectName("lb_warning")
        self.horizontalLayout_12.addWidget(self.lb_warning)
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem36)
        self.pushbt_reset = QtWidgets.QPushButton(Form)
        self.pushbt_reset.setStyleSheet("background-color: #f4511e;\n"
                                        "color: white;\n"
                                        "padding: 16px 32px;\n"
                                        "text-align: center;\n"
                                        "font-size: 16px;\n"
                                        "margin: 4px 2px;\n"
                                        "font-weight:bold;")
        self.pushbt_reset.setObjectName("pushbt_reset")
        self.horizontalLayout_12.addWidget(self.pushbt_reset)
        self.pushbt_submit = QtWidgets.QPushButton(Form)
        self.pushbt_submit.setStyleSheet("background-color: #f4511e;\n"
                                         "color: white;\n"
                                         "padding: 16px 32px;\n"
                                         "text-align: center;\n"
                                         "font-size: 16px;\n"
                                         "margin: 4px 2px;\n"
                                         "font-weight:bold;")
        self.pushbt_submit.setObjectName("pushbt_submit")
        self.horizontalLayout_12.addWidget(self.pushbt_submit)
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem37)
        self.horizontalLayout_12.setStretch(0, 1)
        self.horizontalLayout_12.setStretch(1, 10)
        self.horizontalLayout_12.setStretch(2, 1)
        self.horizontalLayout_12.setStretch(3, 2)
        self.horizontalLayout_12.setStretch(4, 2)
        self.horizontalLayout_12.setStretch(5, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 5)
        self.verticalLayout.setStretch(2, 5)
        self.verticalLayout.setStretch(3, 3)
        self.verticalLayout.setStretch(4, 3)
        self.verticalLayout.setStretch(5, 3)
        self.verticalLayout.setStretch(6, 3)
        self.verticalLayout.setStretch(7, 3)
        self.verticalLayout.setStretch(8, 3)
        self.verticalLayout.setStretch(9, 3)
        self.verticalLayout.setStretch(10, 5)
        self.verticalLayout.setStretch(11, 4)
        self.verticalLayout.setStretch(12, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.myaction(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushbt_back.setText(_translate("Form", "Back"))
        self.label.setText(_translate("Form", "Sign Up"))
        self.label_2.setText(_translate("Form", "Name"))
        self.lb_nameico.setText(_translate("Form", "T"))
        self.label_3.setText(_translate("Form", "Username"))
        self.lb_usernameico.setText(_translate("Form", "T"))
        self.label_4.setText(_translate("Form", "Password"))
        self.lb_passwordico.setText(_translate("Form", "T"))
        self.label_5.setText(_translate("Form", "Confirm Password"))
        self.lb_confirmpasswordico.setText(_translate("Form", "T"))
        self.label_6.setText(_translate("Form", "Phone"))
        self.lb_phoneico.setText(_translate("Form", "T"))
        self.label_7.setText(_translate("Form", "Email"))
        self.lb_emailico.setText(_translate("Form", "T"))
        self.label_8.setText(_translate("Form", "Recovery Hint"))
        self.lb_recoveryhintico.setText(_translate("Form", "T"))
        self.groupBox.setTitle(_translate("Form", "Admin Details"))
        self.label_10.setText(_translate("Form", "Username"))
        self.label_11.setText(_translate("Form", "Password"))
        self.lb_admindetailsico.setText(_translate("Form", "T"))
        self.lb_warning.setText(_translate("Form", "Enter Details"))
        self.pushbt_reset.setText(_translate("Form", "Reset"))
        self.pushbt_submit.setText(_translate("Form", "Submit"))

    def myaction(self, Form):
        from code.images import im_enter
        self.lb_nameico.setPixmap(im_enter)
        self.lb_usernameico.setPixmap(im_enter)
        self.lb_passwordico.setPixmap(im_enter)
        self.lb_confirmpasswordico.setPixmap(im_enter)
        self.lb_phoneico.setPixmap(im_enter)
        self.lb_emailico.setPixmap(im_enter)
        self.lb_recoveryhintico.setPixmap(im_enter)
        self.lb_admindetailsico.setPixmap(im_enter)

        onlyint = QtGui.QIntValidator()
        self.le_phone.setValidator(onlyint)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

